version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: communitypulse
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: 
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/backend

volumes:
  postgres_data:
